# program for demonstrating arithmetic operations
# ArithmeticOperation2.py
a=int(input("Enter value of a:"))
b=int(input("Enter value of b:"))
print("*"*50)
print("\t Arithmetic Operators Results")
print("*"*50)
print("\t{}+{}={}".format(a,b,a+b))
print("\t{}+{}={}".format(a,b,a-b))
print("\t{}+{}={}".format(a,b,a*b))
print("\t{}+{}={}".format(a,b,a/b))
print("\t{}+{}={}".format(a,b,a//b))
print("\t{}+{}={}".format(a,b,a%+b))
print("\t{}+{}={}".format(a,b,a**b))
print("*"*50)